# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ElBanco' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElBanco
   use_frameworks!
  pod 'FlexLayout'
  pod 'PinLayout'
  pod 'lottie-ios'
  pod "KRProgressHUD"

  target 'ElBancoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ElBancoUITests' do
    # Pods for testing
  end

end
